// Code generated by hertz generator.

package tiktokapi

import (
	"context"
	tiktokapi "github.com/PICOF/simple-tiktok/cmd/api/biz/model/tiktokapi"
	"github.com/PICOF/simple-tiktok/cmd/api/biz/rpc"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetVideoList .
// @router /douyin/feed/ [GET]
func GetVideoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokapi.FeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := rpc.GetVideoList(ctx, &req)

	if err != nil {
		msg := "请求远程服务时出错"
		c.JSON(consts.StatusInternalServerError, tiktokapi.FeedResponse{
			StatusCode: -1,
			StatusMsg:  &msg,
			NextTime:   nil,
			VideoList:  nil,
		})
	} else {
		c.JSON(consts.StatusOK, resp)
	}
}
