// Code generated by hertz generator.

package tiktokapi

import (
	"context"
	"github.com/PICOF/simple-tiktok/cmd/api/biz/rpc/message"

	tiktokapi "github.com/PICOF/simple-tiktok/cmd/api/biz/model/tiktokapi"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SendMessage .
// @router /douyin/message/action/ [POST]
func SendMessage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokapi.MessageRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userId := c.GetInt64("user_id")
	resp, err := message.SendMessage(ctx, &req, userId)

	if err != nil && resp == nil {
		msg := "请求远程服务时出错"
		c.JSON(consts.StatusInternalServerError, tiktokapi.LoginResponse{
			StatusCode: -1,
			StatusMsg:  &msg,
		})
	} else {
		c.JSON(consts.StatusOK, resp)
	}
}

// GetChatRecord .
// @router /douyin/message/chat/ [GET]
func GetChatRecord(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokapi.ChatRecordRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userId := c.GetInt64("user_id")
	resp, err := message.GetChatRecord(ctx, &req, userId)

	if err != nil && resp == nil {
		msg := "请求远程服务时出错"
		c.JSON(consts.StatusInternalServerError, tiktokapi.LoginResponse{
			StatusCode: -1,
			StatusMsg:  &msg,
		})
	} else {
		c.JSON(consts.StatusOK, resp)
	}
}
