// Code generated by hertz generator.

package tiktokapi

import (
	"context"
	"github.com/PICOF/simple-tiktok/cmd/api/biz/rpc/relation"

	tiktokapi "github.com/PICOF/simple-tiktok/cmd/api/biz/model/tiktokapi"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FollowAction .
// @router /douyin/relation/action/ [POST]
func FollowAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokapi.FollowRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userId := c.GetInt64("user_id")
	resp, err := relation.FollowAction(ctx, &req, userId)

	if err != nil && resp == nil {
		msg := "请求远程服务时出错"
		c.JSON(consts.StatusInternalServerError, tiktokapi.LoginResponse{
			StatusCode: -1,
			StatusMsg:  &msg,
		})
	} else {
		c.JSON(consts.StatusOK, resp)
	}
}

// GetFollowList .
// @router /douyin/relation/follow/list/ [GET]
func GetFollowList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokapi.RelationListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userId := c.GetInt64("user_id")
	resp, err := relation.GetFollowList(ctx, &req, userId)

	if err != nil && resp == nil {
		msg := "请求远程服务时出错"
		c.JSON(consts.StatusInternalServerError, tiktokapi.LoginResponse{
			StatusCode: -1,
			StatusMsg:  &msg,
		})
	} else {
		c.JSON(consts.StatusOK, resp)
	}
}

// GetFollowerList .
// @router /douyin/relation/follower/list/ [GET]
func GetFollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokapi.RelationListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userId := c.GetInt64("user_id")
	resp, err := relation.GetFollowerList(ctx, &req, userId)

	if err != nil && resp == nil {
		msg := "请求远程服务时出错"
		c.JSON(consts.StatusInternalServerError, tiktokapi.LoginResponse{
			StatusCode: -1,
			StatusMsg:  &msg,
		})
	} else {
		c.JSON(consts.StatusOK, resp)
	}
}

// GetFriendList .
// @router /douyin/relation/friend/list/ [GET]
func GetFriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokapi.RelationListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userId := c.GetInt64("user_id")
	resp, err := relation.GetFriendList(ctx, &req, userId)

	if err != nil && resp == nil {
		msg := "请求远程服务时出错"
		c.JSON(consts.StatusInternalServerError, tiktokapi.LoginResponse{
			StatusCode: -1,
			StatusMsg:  &msg,
		})
	} else {
		c.JSON(consts.StatusOK, resp)
	}
}
