MySQL:
  DSN:
    username: root
    password: niftyjetcar287
    host: localhost
    port: 3306
    database: tiktok
    charset: utf8mb4
    parseTime: true
    location: Local
  connPool:
    maxIdleConn: 10
    maxOpenConn: 100
    connMaxLifetime: 60 # 单位：分钟

