server:
	kitex -module github.com/PICOF/simple-tiktok idl/feed.thrift # execute in the project root directory
	kitex -module github.com/PICOF/simple-tiktok -service feed -use github.com/PICOF/simple-tiktok/kitex_gen ../../idl/feed.thrift